trigger:
  batch: true
  branches:
    include:
    - dev
  paths:
    exclude:
    - README.md


variables:
  agentOS: ubuntu-latest
  
  azKeyVault: key-vault-greencity
  jsonSecret: google-credentials
  jsonFile: google-creds.json
  jsonLocation: /site/wwwroot
  
  artifactName: drop
  coreRepoName: core
  onbootJarName: app.jar
  
  azureSub: GreenCity2022
  resourceGroup: GreenCity
  coreServiceName: greencity

stages:
- stage: Build
  jobs: 
  - job: Build
    pool:
      vmImage: $(agentOS)
    steps:
    - task: Maven@3
      displayName: Maven package
      inputs:
        mavenPomFile: 'pom.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        mavenVersionOption: 'Default'
        options: '-Dmaven.test.skip=true'

    - script: mv $(coreRepoName)/target/*.jar $(coreRepoName)/target/$(onbootJarName)
      displayName: Rename core jar to app

    - task: CopyFiles@2
      displayName: Copy Files
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)'
        Contents: '**/target/*.jar'
        TargetFolder: '$(build.artifactstagingdirectory)'
    
    - task: CopyFiles@2
      displayName: Copy Files
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)/greencity-chart'
        Contents: '**'
        TargetFolder: '$(build.artifactstagingdirectory)/greencity-chart'

    - task: PublishBuildArtifacts@1
      displayName: Publish Artifact
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        artifactName: '$(artifactName)'
        
    - task: Docker@2
      displayName: Build image
      inputs:
        containerRegistry: 'Dockerhub_Skyere'
        repository: 'skyere/greencity'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        tags: |
          $(Build.BuildId)

- stage: Deploy
  jobs:
    - deployment: DeployCore
      displayName: Deploy core app service
      pool:
        vmImage: $(agentOS)
      environment: 'prod'
      strategy:
        runOnce:
          deploy:
            steps:
            - download: none
            
            - task: DownloadBuildArtifacts@0
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: '$(artifactName)'
                downloadPath: '$(System.ArtifactsDirectory)'

            - task: HelmInstaller@0
              inputs:
                helmVersion: '3.9.0'
                installKubectl: true
                
            - task: HelmDeploy@0
              inputs:
                connectionType: 'Kubernetes Service Connection'
                kubernetesServiceConnection: 'k8s-stage'
                namespace: 'default'
                command: 'upgrade'
                chartType: 'FilePath'
                chartPath: '$(System.ArtifactsDirectory)/drop/greencity-chart'
                releaseName: 'greencity'
                overrideValues: 'deployment.image=skyere/greencity:$(Build.BuildId)'
                arguments: '--debug'
