{{- if eq .Values.environment "prod" }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secret-store
spec:
  provider:
    azurekv:
      tenantId: "6c51c659-9d52-41af-81f7-dde16380e813"
      vaultUrl: "https://greencity-app.vault.azure.net"


      authSecretRef:
        # points to the secret that contains
        # the azure service principal credentials
        clientId:
          name: azure-secret-sp
          key: ClientID
          namespace: default

        clientSecret:
          name: azure-secret-sp
          key: ClientSecret
          namespace: default
{{- end }}