{{- if eq .Values.environment "prod" }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secret-store
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      tenantId: {{ .Values.externalSecret.tenantId }}
      vaultUrl: {{ .Values.externalSecret.vaultUrl }}
      serviceAccountRef:
        name: external-secret
{{- end }}
