apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
spec:
  refreshInterval: 168h
  secretStoreRef:
    kind: SecretStore
    name: secret-store

  target:
    name: appsecret
    creationPolicy: Owner

  data:
  # name of the SECRET in the Azure KV (no prefix is by default a SECRET)

  - secretKey: AZURE-CONTAINER-NAME
    remoteRef:
      key: AZURE-CONTAINER-NAME

  - secretKey: APPLICATIONINSIGHTS-CONNECTION-STRING
    remoteRef:
      key: APPLICATIONINSIGHTS-CONNECTION-STRING

  - secretKey: GREENCITYUSER-SERVER-ADDRESS
    remoteRef:
      key: GREENCITYUSER-SERVER-ADDRESS

  - secretKey: FACEBOOK-APP-SECRET
    remoteRef:
      key: FACEBOOK-APP-SECRET

  - secretKey: FACEBOOK-APP-ID
    remoteRef:
      key: FACEBOOK-APP-ID

  - secretKey: BUCKET-NAME
    remoteRef:
      key: BUCKET-NAME

  - secretKey: CACHE-SPEC
    remoteRef:
      key: CACHE-SPEC

  - secretKey: LOG-PATTERN
    remoteRef:
      key: LOG-PATTERN

  - secretKey: LOG-FILE
    remoteRef:
      key: LOG-FILE

  - secretKey: LOG-PATH
    remoteRef:
      key: LOG-PATH

  - secretKey: LOG-EXCEPTION-HANDLER
    remoteRef:
      key: LOG-EXCEPTION-HANDLER

  - secretKey: LOG-LEVEL-ROOT
    remoteRef:
      key: LOG-LEVEL-ROOT

  - secretKey: VERIFY-EMAIL
    remoteRef:
      key: VERIFY-EMAIL

  - secretKey: TOKEN-KEY
    remoteRef:
      key: TOKEN-KEY

  - secretKey: TOKEN-REFRESH-TIME
    remoteRef:
      key: TOKEN-REFRESH-TIME

  - secretKey: TOKEN-ACCESS-TIME
    remoteRef:
      key: TOKEN-ACCESS-TIME

  - secretKey: ECO-NEWS-ADDRESS
    remoteRef:
      key: ECO-NEWS-ADDRESS

  - secretKey: CLIENT-ADDRESS
    remoteRef:
      key: CLIENT-ADDRESS

  - secretKey: BACKEND-ADDRESS
    remoteRef:
      key: BACKEND-ADDRESS

  - secretKey: SMTP-ENABLE
    remoteRef:
      key: SMTP-ENABLE

  - secretKey: SMTP-AUTH
    remoteRef:
      key: SMTP-AUTH

  - secretKey: MAIL-PASSWORD
    remoteRef:
      key: MAIL-PASSWORD

  - secretKey: MAIL-USER
    remoteRef:
      key: MAIL-USER

  - secretKey: MAIL-PORT
    remoteRef:
      key: MAIL-PORT

  - secretKey: MAIL-HOST
    remoteRef:
      key: MAIL-HOST

  - secretKey: JDBC-LOB
    remoteRef:
      key: JDBC-LOB

  - secretKey: SHOW-SQL
    remoteRef:
      key: SHOW-SQL

  - secretKey: DIALECT
    remoteRef:
      key: DIALECT

  - secretKey: HIBERNATE-CONFIG
    remoteRef:
      key: HIBERNATE-CONFIG

  - secretKey: LIQUIBASE-LOG
    remoteRef:
      key: LIQUIBASE-LOG

  - secretKey: LIQUIBASE-ENABLE
    remoteRef:
      key: LIQUIBASE-ENABLE

  - secretKey: POOL-SIZE
    remoteRef:
      key: POOL-SIZE

  - secretKey: DRIVER
    remoteRef:
      key: DRIVER

  - secretKey: DATABASE-PASSWORD
    remoteRef:
      key: DATABASE-PASSWORD

  - secretKey: DATABASE-USER
    remoteRef:
      key: DATABASE-USER

  - secretKey: JAWSDB-URL
    remoteRef:
      key: JAWSDB-URL

  - secretKey: JAWSDB-URL-UBS
    remoteRef:
      key: JAWSDB-URL-UBS

  - secretKey: AZURE-CONNECTION-STRING
    remoteRef:
      key: AZURE-CONNECTION-STRING

  - secretKey: API-SECRET
    remoteRef:
      key: API-SECRET

  - secretKey: API-KEY
    remoteRef:
      key: API-KEY

  - secretKey: SPRING-PROFILES-ACTIVE
    remoteRef:
      key: SPRING-PROFILES-ACTIVE
  
  - secretKey: MERCHANT-ID
    remoteRef:
      key: MERCHANT-ID
  
  - secretKey: LIQPAY-PUBLIC-KEY
    remoteRef:
      key: LIQPAY-PUBLIC-KEY
  
  - secretKey: LIQPAY-PRIVATE-KEY
    remoteRef:
      key: LIQPAY-PRIVATE-KEY
  
  - secretKey: FONDY-PAYMENT-KEY
    remoteRef:
      key: FONDY-PAYMENT-KEY
  
  - secretKey: TELEGRAM-BOT-TOKEN
    remoteRef:
      key: TELEGRAM-BOT-TOKEN
  
  - secretKey: TELEGRAM-BOT-NAME
    remoteRef:
      key: TELEGRAM-BOT-NAME
  
  - secretKey: VIBER-BOT-TOKEN
    remoteRef:
      key: VIBER-BOT-TOKEN
  
  - secretKey: VIBER-BOT-URI
    remoteRef:
      key: VIBER-BOT-URI
  
  - secretKey: VIBER-BOT-URL
    remoteRef:
      key: VIBER-BOT-URL
  
  - secretKey: GREENCITY-CHAT-SERVER-ADDRESS
    remoteRef:
      key: GREENCITY-CHAT-SERVER-ADDRESS
  
  - secretKey: GREENCITY-SERVER-ADDRESS
    remoteRef:
      key: GREENCITY-SERVER-ADDRESS
  
  - secretKey: GOOGLE-CLIENT-ID-MANAGER
    remoteRef:
      key: GOOGLE-CLIENT-ID-MANAGER
  
  - secretKey: GOOGLE-CLIENT-ID
    remoteRef:
      key: GOOGLE-CLIENT-ID
  
  - secretKey: BACKEND-ADDRESS-USER
    remoteRef:
      key: BACKEND-ADDRESS-USER

  - secretKey: STATIC-URL
    remoteRef:
      key: STATIC-URL

  - secretKey: EMAIL-TOPIC
    remoteRef:
      key: EMAIL-TOPIC

  - secretKey: SENDER-EMAIL-ADDRESS
    remoteRef:
      key: SENDER-EMAIL-ADDRESS

  - secretKey: AZURE-CONTAINER
    remoteRef:
      key: AZURE-CONTAINER

  - secretKey: AZURE-CONNECTION 
    remoteRef:
      key: AZURE-CONNECTION

  - secretKey: LIQPAY-REDIRECT
    remoteRef:
      key: LIQPAY-REDIRECT

  - secretKey: FONDY-PERSONAL-CABINET
    remoteRef:
      key: FONDY-PERSONAL-CABINET

  - secretKey: FONDY-REDIRECT
    remoteRef:
      key: FONDY-REDIRECT

  - secretKey: GOOGLE-API-KEY
    remoteRef:
      key: GOOGLE-API-KEY


